### ISSUE TITLE
:shield: Couplage SonarQ

### ISSUE THREAD

**Issue by adriens** [adriens/api-forfaits-opt#2]

**Comment by adriens** [comment]
![image](https://github.com/user-attachments/assets/d27c1095-bd26-417f-99c7-e6c1621c8eba)

**Comment by adriens** [comment]
![image](https://github.com/user-attachments/assets/4038c4c0-80b9-423e-a8f6-4c9f7c0cba42)

**Comment by adriens** [comment]
Faudra ajouter ceci au `pom.xml`: 

![image](https://github.com/user-attachments/assets/2bc9575f-d32c-4b14-a51b-a81d615079ab)

```xml
<properties>
  <sonar.organization>adriens</sonar.organization>
  <sonar.host.url>https://sonarcloud.io</sonar.host.url>
</properties>
```

... et compléter `.github/workflows/build.yml` : 

```yaml
name: SonarQube
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=adriens_api-forfaits-opt
```

**Comment by adriens** [comment]
En attente de l'arrivée du build et de la ci
:pause_button:

**Comment by morgancarre** [comment]
> Faudra ajouter ceci au `pom.xml`:
> 
> ![image](https://private-user-images.githubusercontent.com/5235127/393647246-2bc9575f-d32c-4b14-a51b-a81d615079ab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzYxOTgwODIsIm5iZiI6MTczNjE5Nzc4MiwicGF0aCI6Ii81MjM1MTI3LzM5MzY0NzI0Ni0yYmM5NTc1Zi1kMzJjLTRiMTQtYTUxYi1hODFkNjE1MDc5YWIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDZUMjEwOTQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njg4YmZkOTM1Njk5MTM0M2M5YTZiY2NhZDU2YzUxMjNlYmVhMGE1MjI1YjgwNmE4ZmVlZjFmMzc3ZjAxMzY2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ZKudJprTKczTzrt3h7rNcEOk5PIMx1IAQtkWr3g8epI)
> 
> ```
> <properties>
>   <sonar.organization>adriens</sonar.organization>
>   <sonar.host.url>https://sonarcloud.io</sonar.host.url>
> </properties>
> ```
> 
> ... et compléter `.github/workflows/build.yml` :
> 
> ```yaml
> name: SonarQube
> on:
>   push:
>     branches:
>       - main
>   pull_request:
>     types: [opened, synchronize, reopened]
> jobs:
>   build:
>     name: Build and analyze
>     runs-on: ubuntu-latest
>     steps:
>       - uses: actions/checkout@v4
>         with:
>           fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
>       - name: Set up JDK 17
>         uses: actions/setup-java@v4
>         with:
>           java-version: 17
>           distribution: 'zulu' # Alternative distribution options are available.
>       - name: Cache SonarQube packages
>         uses: actions/cache@v4
>         with:
>           path: ~/.sonar/cache
>           key: ${{ runner.os }}-sonar
>           restore-keys: ${{ runner.os }}-sonar
>       - name: Cache Maven packages
>         uses: actions/cache@v4
>         with:
>           path: ~/.m2
>           key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
>           restore-keys: ${{ runner.os }}-m2
>       - name: Build and analyze
>         env:
>           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
>           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
>         run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=adriens_api-forfaits-opt
> ```

Je peux fusionner ce workflow à celui que j'ai déjà ? 

```
name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v2
        with:
          java-version: '23'
          distribution: 'zulu'

      # si couverture de code inférieur a 10 % alors le build échoue.  
      - name: Build and run tests with Maven
        run: mvn clean verify
```

ou le mieux c'est de créer un nouveau workflow a part ?
