### ISSUE TITLE
:test_tube:  Tester `bump.sh`

### ISSUE THREAD

**Issue by adriens** [adriens/api-forfaits-opt#3]
- [x] COmprendre ce qu'est https://bump.sh/
- [x] Mettre en oeuvre
- [x] Comparer avec redocly
- [ ] Expliquer relation avec microcks
- [x] DOnner du feedback

**Comment by morgancarre** [comment]
J'ai regardé comment implémenter bump.sh avec les GitHub Actions. Mais il faudrait que je puisse avoir accès aux paramètres du dépôt pour pouvoir ajouter un 'secret GitHub', car j'ai une clé API que je dois utiliser dans le workflow.

```
name: Check & deploy API documentation
permissions:
  contents: read
  pull-requests: write
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  deploy-doc:
    if: ${{ github.event_name == 'push' }}
    name: Deploy API documentation on Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: morgancarre
          token: ********************************
          file: doc/api-documentation.yml
  api-diff:
    if: ${{ github.event_name == 'pull_request' }}
    name: Check API diff on Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Comment pull request with API diff
        uses: bump-sh/github-action@v1
        with:
          doc: morgancarre
          token: ********************************
          file: doc/api-documentation.yml
          command: diff
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
